feat: adicionado componente Radio
eitri-tech/luminus-daisy pull request #17
Opened 2024-07-19 17:25 UTC by lucassdr

![image](https://github.com/user-attachments/assets/ad5e202b-d07c-40d4-a561-b671991e0360)

2024-07-19 18:52 UTC, omarcelomadeira requested changes

2024-07-19 18:52 UTC, omarcelomadeira commented on examples/src/blocks/dataInput/radio.jsx
> +        setChecked(event.target.value);
Aqui, até por conta do nosso modo de desenvolvimento mais próximo do mobile, o ideal é que o argumento chamado na função já seja o valor e não o evento em si, pois o evento é um objeto do DOM

2024-07-19 19:13 UTC, lucassdr commented on examples/src/blocks/dataInput/radio.jsx
> +        setChecked(event.target.value);
Hm... bom ponto.
Farei dessa forma.

2024-07-22 16:59 UTC, omarcelomadeira approved these changes

2024-07-22 17:01 UTC, merged