feat: Add FullScreen component
eitri-tech/luminus-daisy pull request #63
Opened 2024-09-04 20:41 UTC by VitorAugusto

2024-09-04 20:45 UTC, lucassdr commented
@VitorAugusto ficou faltando o exemplo.

2024-09-04 20:45 UTC, lucassdr requested changes
Ficou faltando o exemplo de uso da funcionalidade.

2024-09-04 20:57 UTC, omarcelomadeira requested changes

2024-09-04 20:57 UTC, omarcelomadeira commented on src/components/Others/Fullscreen/fullscreen.tsx
> +                style={{
Você pode tentar encontrar uma classe CSS para fazer o toggle entre flex e none, acho que o tailwind tem as duas opções, aí eliminamos esse style inline

2024-09-04 20:58 UTC, omarcelomadeira commented
> Ficou faltando o exemplo de uso da funcionalidade.

Eu dei um bypass por ele, na verdade esse componente é caminho para um outro. Aí a gente usa os dois no examples

2024-09-05 15:01 UTC, omarcelomadeira approved these changes

2024-09-05 15:01 UTC, merged